name: run and bulid
on: [push]
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
         - name: mycode
           uses: actions/checkout@v2
        
         - name: run one line script
           run: echo raghu

         - name: run multi line
           run: 
            echo add other actions to built,
            echo test, and deploy

    build-api:
       runs-on: ubuntu-latest
       steps:
          - run: echo"building api"
    
    build-db:
        needs: build-api
        runs-on: ubuntu-latest
        steps:
          - run: echo "needs added"

    package: 
       needs: [build-api, build-db]
       runs-on: ubuntu-latest
       steps:
          - run: echo "packaging"